name: Build and Test Java Spring Boot Application 
 
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn compile
  test:
    needs: build  # Espera a que termine `build`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn test
      - name: Upload Test Report
        if: success() || failure()  # Asegura que se suba el reporte incluso si fallan los tests
        uses: actions/upload-artifact@v4
        with:
          name: SpringBoot Report
          path: target/site/
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Step
        run: echo "En construcción ..."
